version: '3.1'
services:
  odoo:
    build: .
    image: fb-image
    depends_on:
      - mydb
    restart: always
    ports:
      - "8071:8069"
    volumes:
      - odoo-web-data2:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/extra-addons
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata/fundboard/
    volumes:
      - odoo-db-data2:/var/lib/postgresql/data/pgdata/fundboard/
    
volumes:
  odoo-web-data2:
  odoo-db-data2:
